version: '3.8'

services:
  service:
    container_name: user_service_container
    build:
      context: .
      dockerfile: build/docker/service/Dockerfile
    restart: unless-stopped
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    links:
      - db
    depends_on:
      - db
    env_file:
      .env

  db:
    image: postgres:15-alpine
    container_name: user_service_db_container
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgres/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      .env

volumes:
  pg_data:
